global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: emar-backend
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets:
          - app.example.com
    authorization:
      type: Bearer
      credentials: replace_with_metrics_token
    headers:
      x-metrics-token: 46501beb275aa5ba0516da1f7bc4ae8ba56b31e95b32aca507800dcfe13e8460